# Generated by Django 5.2.4 on 2025-07-13 07:21

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resources/', validators=[core.models.validate_file_extension])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('department', models.CharField(choices=[('AI&DS', 'Artificial Intelligence & Data Science'), ('cse', 'Computer Science & Engineering'), ('ee', 'Electrical Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('che', 'Chemical Engineering'), ('mme', 'Metallurgical & Materials Engineering'), ('ece', 'Electronics & Communication Engineering'), ('arch', 'Architecture & Planning')], default='cse', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject_other', models.CharField(blank=True, help_text='If you selected Other, please specify.', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'title', 'file'), name='unique_user_title_file')],
            },
        ),
    ]
