# Generated by Django 5.2.4 on 2025-07-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='year',
        ),
    ]
