# Generated by Django 5.2.4 on 2025-07-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pdfresource_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource'),
        ),
    ]
