# Generated by Django 5.2.4 on 2025-07-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bookmark_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureAndPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='category_images/')),
            ],
        ),
    ]
