# Generated by Django 5.2.4 on 2025-07-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_architectureandplanning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchitectureAndPlanning',
        ),
    ]
