# Generated by Django 5.2.4 on 2025-07-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='year',
        ),
    ]
