# Generated by Django 5.2.4 on 2025-07-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('ee', 'Electrical Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('che', 'Chemical Engineering'), ('mme', 'Metallurgical & Materials Engineering'), ('ece', 'Electronics & Communication Engineering'), ('arch', 'Architecture & Planning'), ('phy', 'Physics'), ('chem', 'Chemistry'), ('math', 'Mathematics'), ('hss', 'Humanities & Social Sciences')], default='cse', max_length=40),
        ),
    ]
