# Generated by Django 5.2.4 on 2025-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_resource_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subject_other',
            field=models.CharField(blank=True, help_text='If you selected Other, please specify.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('ee', 'Electrical Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('che', 'Chemical Engineering'), ('mme', 'Metallurgical & Materials Engineering'), ('ece', 'Electronics & Communication Engineering'), ('arch', 'Architecture & Planning'), ('AI&DS', 'Artificial Intelligence & Data Science')], default='cse', max_length=40),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(choices=[('phy', 'Physics'), ('chem', 'Chemistry'), ('math', 'Mathematics'), ('bio', 'Biology'), ('other', 'Other')], max_length=100),
        ),
    ]
