# Generated by Django 5.2.3 on 2025-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_page_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='released_year',
            field=models.IntegerField(default=2025),
        ),
    ]
